sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: aZKWtrJprfAgQXMJl7gxiHu8GLm56KgQ0ltetWE0KfK/mlwHGSznwps+Qr796W4kxCbe7ZLBP8B9DYLSAmt68T6vzLP/X7U4pDFXygIy8pT82j2ktZ3Jl3orNnabe+uQLox5qw+sc0pq18egx0QDHHRzJ+35xEr9INKQ2GlT7JDcICtpz43fJbfA1D7FtiIZOlIJv2aNx5pCEQEJIijm22XqVGT6anadWWsW251VRoO/yM6yRBVEiUsL5RhTcqxSj9yn+L1urcF/SAi+FrzVOxveleT0gwenNktzvllqH3+URFty2DrJT2NcFB/Hrwv4sQCwWb1sQy1zy/QLvbgYPh5vBA5Zf1wvjTy41NEYWZ/xlqpeU0mbZFBzcuPdX4tnaDTbGVrXMMYJroeLZUxQ/Mnom1zc/q0HzqsSIBqP3UvgQRo1vwNoJQMQWLYYnfcmb6DBDyMmdaOKUeywWpjf2+fi9OfgqE60ri/FeSQdg/kLzwL4r02kyAuO6msA9vwNa4iw8FWm/EqXo0zLzlTf345163f+nGACSndE/DNyUv6trMlMJq/kuISBnLCFTd8VWmdyckZj/kuzzUMvWDOWtJNQF1HGx11HHxVfGtAfgF6h96CupK/47j4glqgzfVSzoZT+A3J7/zJnOZ0jl2IMOENsP2JHSesWwyD1IMt24is=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Her-Father-s-Daughter_904
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy